### ISSUE TITLE
运行出错，获取不到名字

### ISSUE THREAD

**Issue by lxy-coder** [zzzjoy-620/ctgu_book_seat#2]
获取不到名字啊，也约不了，请问怎么回事啊，大佬求解
日志：
ERROR RequestId: 2f19a49d-fb65-483a-b6d6-6bc4246da02f Result: Traceback (most recent call last):   File "/var/user/index.py", line 228, in main_handler     main()   File "/var/user/index.py", line 223, in main     book_seat_user(user)   File "/var/user/index.py", line 188, in book_seat_user     access_token, name = get_access_token(user['username'], user['password'])   File "/var/user/index.py", line 71, in get_access_token     access_token, name = login(session, username, password)   File "/var/user/index.py", line 48, in login     return dict(session.cookies)['access_token'], name KeyError: 'access_token'

END RequestId: 2f19a49d-fb65-483a-b6d6-6bc4246da02f

**Comment by javencpdd** [comment]
么有token

**Comment by javencpdd** [comment]
黎？
