### ISSUE TITLE
无法获取access_token

### ISSUE THREAD

**Issue by lxy-coder** [zzzjoy-620/ctgu_book_seat#3]
index.py中48行，返回access_token出错，貌似没有获取到access_token。
报错信息：  File "/var/user/index.py", line 49, in login     return dict(session.cookies)['access_token'], name KeyError: 'access_token'

**Comment by lxy-coder** [comment]
48行前添加logger.info(session.cookies)：输出日志：

<RequestsCookieJar[<Cookie JSESSIONID=E32C2EB25EBFE3D9ACBE9DF7486A3974 for cas.lib.ctgu.edu.cn/cas>, <Cookie CASTGC=TGT-168352-Go6wkuhPdolrfxFbXwnD3jvt4rpBK2IuPfXakVm9fpMpQilIZO-sso.cqvip.com for cas.lib.ctgu.edu.cn/cas/>, <Cookie PHPSESSID=pgkb6ah4c1mp7am6qk2alolam5 for zwyy.lib.ctgu.edu.cn/>, <Cookie PHPSESSID_NS_Sig=oenCV6mf2Wl77Ai_ for zwyy.lib.ctgu.edu.cn/>, <Cookie redirect_url=%2Fhome%2Fweb%2Fseat%2Farea%2F1 for zwyy.lib.ctgu.edu.cn/>]>

**Comment by Kerim620** [comment]
项目不更新了，有问题自己看看代码改改吧
